apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift
    app.kubernetes.io/part-of: hypershift-operator-main-hotfix
  name: hypershift
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: hypershift
status:
  loadBalancer: {}
